name: Publish to PyPi

on:
  push:
     tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-test'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Extract version from tag
      id: get_version
      run: |
        # Remove 'v' prefix and '-test' suffix
        TAG=${GITHUB_REF#refs/tags/v}
        VERSION=${TAG%-test}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.13'
    - name: Instal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build distribution
      run: make build_distribution
      env:
        PACKAGE_VERSION: ${{ env.VERSION }}
    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.SECRET_PYPI }}
      run: make upload_to_testpypi
        

    
    
    
