name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: "Run tests with coverage"
        run: pytest -vv --cov=src 
    lint:
      needs: testing
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: read
        statuses: write
      steps:
          







        
      
